substitutions:
  name: zone-controller
  friendly_name: Heating Zone Controller
  area: ""

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${area}
 # name_add_mac_suffix: true
  project:
    name: heating.zone-controller
    version: 1.0.0
  on_boot:
    then:
      # read the RTC time once when the system boots
      ds1307.read_time:
  includes: <nvs_flash.h>
esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended

external_components:
  - source:
      type: local
      path: custom_components


# Enable logging
logger:
  level: VERY_VERBOSE
  logs:
    light.addressable: DEBUG
    api.service: DEBUG

# Enable Home Assistant API
api:
   # password: !secret api_password
  encryption: 
    key: !secret api_key
  homeassistant_services: True

ota:
  - platform: esphome
    password: !secret ota_password
    id: zone_controller_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Static IP
  manual_ip:
    static_ip: 192.168.68.60
    gateway: 192.168.68.1
    subnet: 255.255.255.0
#    dns1: 192.168.1.254
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password
http_request:
  id: http_request_data
  useragent: esphome/sched
  timeout: 10s
  verify_ssl: false
globals:
  - id: ipInfodata
    type: std::string
    restore_value: no
    initial_value: '""'

captive_portal:

web_server:
  port: 80
#event:
#   - platform: template #  Base event platform
 #    id: my_webhook_event  
    
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true    
  id: bus_1
time:
  - platform: ds1307
    id: rtc_time
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: never
  - platform: homeassistant
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:

# dashboard_import:
#  package_import_url: github://ryansch/esphome-config/waveshare-esp32-s3-relay-6ch.yaml



binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    name: "Boot Button"
    pin:
      number: 0
      ignore_strapping_warning: true
      mode:
        input: true
      inverted: true
    disabled_by_default: true
    on_press:
      then:
        - button.press: restart_button

text_sensor:
  - platform: version
    name: "Firmware Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic

switch:
  - platform: schedule
    id: testschedule
    name: "Test Schedule Switch"
    ha_schedule_entity_id: "schedule.test_sche"
    max_schedule_size: 100
    schedule_update_button: Update Schedule
    schedule_switch_indicator: 
      name: "Test Schedule Active"
    current_event:
      name: "Current Event"
    next_event:
      name: "Next Event"
    mode_selector:
      name: "Schedule Mode" 
    scheduled_data_items:
      - id: temp_sensor
        label: "temp"
        item_type: float
        name: "Schedule Temperature"
        item_behavior_when_off: OFF_VALUE
        item_off_value: 21.5
        item_behavior_in_manual_on: MANUAL_VALUE
        item_manual_on_value: 22.0
    on_turn_on:
      - lambda: |-
          float temp = SCHEDULE_GET_DATA(testschedule, "temp");
          ESP_LOGI("schedule", "Switch ON - Temperature: %.1f°C", temp);

  - platform: schedule
    id: testschedule2
    name: "Test Schedule Switch2"
    ha_schedule_entity_id: "schedule.test2"
    max_schedule_size: 20
    schedule_update_button: Update Schedule2
    schedule_switch_indicator: 
      id: test_schedule2_active
      name: "Test Schedule2 Active"
    current_event:
      name: "Current Event2"
    next_event:
      name: "Next Event2"
    mode_selector:
      name: "Schedule 2 Mode"
      id: schedule_2_mode
    scheduled_data_items:
      - id: temp_sensor2
        label: "temp"
        item_type: float
        name: "Schedule2 Temperature"
        item_behavior_when_off: LAST_ON_VALUE
        item_off_value: 21.5
        item_behavior_in_manual_on: MANUAL_VALUE
        item_manual_on_value: 22.0
    on_turn_on:
      - logger.log: "Test Schedule 2 Switch Turned ON"
    on_turn_off:
      - logger.log: "Test Schedule 2 Switch Turned OFF"  
  - platform: gpio
    pin: GPIO1
    id: relay1
    name: Relay 1
    on_turn_on:
      - lambda: 'auto call = id(schedule_2_mode).make_call(); 
                 call.set_option("Manual On");
                 call.perform();'
  - platform: gpio
    pin: GPIO2
    id: relay2
    on_turn_on:
      - lambda: 'auto call = id(schedule_2_mode).make_call(); 
                 call.set_option("Manual Off");
                 call.perform();'
    name: Relay 2
  - platform: gpio
    pin: GPIO41
    id: relay3
    name: Relay 3
    on_turn_on:      
      - lambda: 'id(testschedule).load_schedule_from_pref_();'
  - platform: gpio
    pin: GPIO42
    id: relay4
    name: Relay 4
    on_turn_on:      
      - lambda: 'id(testschedule).save_schedule_to_pref_();'
  - platform: gpio
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: relay5
    name: Relay 5
    on_turn_on: 
      - lambda: 'id(testschedule).log_schedule_data();'
        
  - platform: gpio
    pin:
      number: GPIO46
      ignore_strapping_warning: true
    id: relay6
    name: Relay 6
    on_turn_on: 
      - lambda: 'id(testschedule).request_schedule();'
uart:
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 9600
  id: modbus_uart


# modbus:
#  id: modbus1
 # uart_id: modbus_uart
#  send_wait_time: 1500ms
#  role: client

#modbus_controller:
#  - id: mod_sensor_1
#    address: 0x02
#    command_throttle: 1000ms
#    update_interval: 60s
#    setup_priority: -10
#    offline_skip_updates: 8

#  - id: mod_sensor_2
#    address: 0x03
 #   command_throttle: 1000ms
#    update_interval: 60s
#    setup_priority: -10
#    offline_skip_updates: 8
    

# buzzer
output:
  - platform: ledc
    pin: GPIO21
    id: buzzer


rtttl:
  output: buzzer
  id: rtttl_buzzer
  gain: 30%

light:
  - platform: esp32_rmt_led_strip
    id: rgb_led
    name: "RGB LED"
    rgb_order: RGB
    pin: GPIO38
    num_leds: 1
    chipset: WS2812

button:
  - platform: restart
    name: "Restart"
    id: restart_button
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    id: reset
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    entity_category: config


  - platform: schedule
    id: fish_feeding_button
    name: "Feed Fish Button"
    ha_schedule_entity_id: "schedule.fish_feeding"
    max_schedule_size: 10
    
    schedule_update_button:
      name: "Update Feeding Schedule"
    
    current_event:
      name: "Current Feeding"
    
    next_event:
      name: "Next Feeding"
    
    mode_selector:
      name: "Feeding Schedule Mode"
    
    # Event-based schedule variables (NO off_behavior or manual_behavior)
    scheduled_data_items:
      - label: "Feed Amount"
        item_type: uint8_t  # 0-255
        name: "Feed Amount Sensor" 
    
    on_press:
      - lambda: |-
          float amount = SCHEDULE_GET_DATA(fish_feeding_button, "Feed Amount");
          ESP_LOGI("schedule", "Feed button pressed - Amount: %.0f", amount);


  - platform: template
    name: "Get NVS Stats"
    id: get_nvs_stats
    on_press:
      - lambda: |-
          
          nvs_stats_t nvs_stats;
          esp_err_t err = nvs_get_stats(NULL, &nvs_stats);
          if (err == ESP_OK) {
            ESP_LOGI("nvs_stats", "Total entries: %u", nvs_stats.total_entries);
            ESP_LOGI("nvs_stats", "Used entries: %u", nvs_stats.used_entries);
            ESP_LOGI("nvs_stats", "Free entries: %u", nvs_stats.free_entries);
            ESP_LOGI("nvs_stats", "Namespace count: %u", nvs_stats.namespace_count);
          } else {
            ESP_LOGE("nvs_stats", "Failed to get NVS stats: %s", esp_err_to_name(err));
          }
# Test buttons that call the template class methods

  - platform: template
    name: "Test Create Preference"
    icon: "mdi:database-plus"
    on_press:
      - lambda: |-
          id(testschedule)->test_create_preference();
  
  - platform: template
    name: "Test Save Preference"
    icon: "mdi:content-save"
    on_press:
      - lambda: |-
          id(testschedule)->test_save_preference();
  
  - platform: template
    name: "Test Load Preference"
    icon: "mdi:download"
    on_press:
      - lambda: |-
          id(testschedule)->test_load_preference();

sensor:
 # - platform: modbus_controller
#    modbus_controller_id: mod_sensor_1
#    name: "Zone 1 Temp"
#   register_type: read
#    address: 0x0001    ## address of the register inside the Modbus slave device
#    unit_of_measurement: "°C"
 #   device_class: "temperature"
#    value_type: S_WORD
 #   accuracy_decimals: 0
#    filters:
#     - lambda: return x / 10;


#  - platform: modbus_controller
#    modbus_controller_id: mod_sensor_1
#    name: "Zone 1 Hum"
#    register_type: read
#    address: 0x0002    ## address of the register inside the Modbus slave device
#    unit_of_measurement: "%"
#    device_class: "humidity"
#    value_type: U_WORD
#    accuracy_decimals: 2
#    filters:
#      - lambda: return x / 10;

#  - platform: modbus_controller
#    modbus_controller_id: mod_sensor_2
#   name: "Zone 2 Temp"
#    register_type: read
#    address: 0x0001    ## address of the register inside the Modbus slave device
#    unit_of_measurement: "°C"
#    device_class: "temperature"
#    value_type: S_WORD
#    accuracy_decimals: 0
#    filters:
 #    - lambda: return x / 10;


 # - platform: modbus_controller
 #   modbus_controller_id: mod_sensor_2
 #   name: "Zone 2 Hum"
 #   register_type: read
 #   address: 0x0002    ## address of the register inside the Modbus slave device
 #   unit_of_measurement: "%"
 #   device_class: "humidity"
  #  value_type: U_WORD
 #   accuracy_decimals: 2
 #   filters:
  #    - lambda: return x / 10;

  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

