# Example: Multi-Action Routines with Schedule Component
# This example demonstrates event-based scheduling for morning and evening routines

substitutions:
  device_name: daily-routines
  friendly_name: Daily Routines

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
 
 # name_add_mac_suffix: true
  project:
    name: hblinds.zone-controller
    version: 1.0.0
  on_boot:
    then:
      # read the RTC time once when the system boots
      ds1307.read_time:

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  homeassistant_services: True
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot
  ap:
    ssid: "${device_name} Fallback"
    password: !secret ap_password

captive_portal:

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true    
  id: bus_1
time:
  - platform: ds1307
    id: rtc_time
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: never
  - platform: homeassistant
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:

# Schedule component
external_components:
  - source:
      type: local
      path: custom_components
    components: [schedule]


button:
  # Morning routine
  - platform: schedule
    id: morning_routine
    name: "Morning Routine"
    ha_schedule_entity_id: "schedule.morning_routine"
    
    schedule_update_button:
      name: "Update Morning Routine"
    
    mode_selector:
      name: "Morning Routine Mode"
    
    scheduled_data_items:
      - id: routine_brightness
        label: "brightness"
        item_type: uint8_t
    
    on_press:
      - logger.log: "Starting morning routine"
      - cover.open: all_blinds
      - delay: 30s
      - lambda: |-
          uint8_t brightness = id(routine_brightness).state;
          if (!isnan(brightness)) {
            auto call = id(living_room_light).turn_on();
            call.set_brightness(brightness / 100.0);
            call.perform();
          }
      - homeassistant.service:
          service: tts.google_say
          data:
            entity_id: media_player.living_room
            message: "Good morning! Time to wake up."

  # Evening routine
  - platform: schedule
    id: evening_routine
    name: "Evening Routine"
    ha_schedule_entity_id: "schedule.evening_routine"
    
    schedule_update_button:
      name: "Update Evening Routine"
    
    mode_selector:
      name: "Evening Routine Mode"
    
    on_press:
      - logger.log: "Starting evening routine"
      - cover.close: all_blinds
      - delay: 30s
      - light.turn_on:
          id: living_room_light
          brightness: 50%
      - switch.turn_on: outdoor_lights

# Example RGB light (replace with your actual light setup)
light:
  - platform: rgb
    id: living_room_light
    name: "Living Room Light"
    red: output_red
    green: output_green
    blue: output_blue

# PWM outputs for RGB light
output:
  - platform: ledc
    id: output_red
    pin: GPIO25
    
  - platform: ledc
    id: output_green
    pin: GPIO26
    
  - platform: ledc
    id: output_blue
    pin: GPIO27

# Example cover for blinds
cover:
  - platform: template
    id: all_blinds
    name: "All Blinds"
    open_action:
      - logger.log: "Opening all blinds"
      # Add your actual motor control logic here
    close_action:
      - logger.log: "Closing all blinds"
      # Add your actual motor control logic here

# Example outdoor lights switch
switch:
  - platform: gpio
    id: outdoor_lights
    pin: GPIO14
    name: "Outdoor Lights"
