# Example: Thermostat with Temperature Control using Schedule Component
# This example demonstrates a scheduled switch controlling a thermostat with temperature data

substitutions:
  device_name: thermostat-controller
  friendly_name: Thermostat Controller

eesphome:
  name: ${name}
  friendly_name: ${friendly_name}
 
 # name_add_mac_suffix: true
  project:
    name: hblinds.zone-controller
    version: 1.0.0
  on_boot:
    then:
      # read the RTC time once when the system boots
      ds1307.read_time:

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
  homeassistant_services: True
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot
  ap:
    ssid: "${device_name} Fallback"
    password: !secret ap_password

captive_portal:

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true    
  id: bus_1
time:
  - platform: ds1307
    id: rtc_time
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: never
  - platform: homeassistant
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:

# Schedule component
external_components:
  - source:
      type: local
      path: custom_components
    components: [schedule]


# Get temperature from Home Assistant
sensor:
  - platform: homeassistant
    id: current_temp
    entity_id: sensor.living_room_temperature

# Thermostat climate control
climate:
  - platform: thermostat
    id: room_thermostat
    name: "Living Room Thermostat"
    sensor: current_temp
    
    default_preset: Home
    on_boot_restore_from: default_preset
    
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    
    heat_action:
      - switch.turn_on: heater_relay
    
    idle_action:
      - switch.turn_off: heater_relay
    
    visual:
      min_temperature: 10째C
      max_temperature: 28째C
      temperature_step: 0.5째C

# Schedule switch with temperature data
switch:
  - platform: schedule
    id: heating_schedule
    name: "Heating Schedule"
    ha_schedule_entity_id: "schedule.heating"
    max_schedule_entries: 21
    
    schedule_update_button:
      name: "Update Heating Schedule"
    
    mode_selector:
      name: "Heating Mode"
    
    current_event_sensor:
      name: "Current Heating Event"
    
    next_event_sensor:
      name: "Next Heating Event"
    
    scheduled_data_items:
      - id: heating_temp
        label: "temperature"
        item_type: float
        name: "Schedule Target Temperature"
        off_behavior: OFF_VALUE
        off_value: 15.0
        manual_behavior: MANUAL_VALUE
        manual_value: 20.0
    
    on_turn_on:
      - lambda: |-
          // Schedule switched ON - set thermostat to HEAT mode with scheduled temperature
          auto target = SCHEDULE_GET_DATA(heating_schedule, "temperature");
          if (!isnan(target)) {
            auto call = id(room_thermostat).make_call();
            call.set_mode(climate::CLIMATE_MODE_HEAT);
            call.set_target_temperature(target);
            call.perform();
            ESP_LOGI("heating", "Schedule ON - heating to %.1f째C", target);
          }
    
    on_turn_off:
      - lambda: |-
          // Schedule switched OFF - turn off thermostat
          auto call = id(room_thermostat).make_call();
          call.set_mode(climate::CLIMATE_MODE_OFF);
          call.perform();
          ESP_LOGI("heating", "Schedule OFF - thermostat off");

  # Physical heater relay
  - platform: gpio
    id: heater_relay
    pin: GPIO5
    internal: true
